/*
 * Vetokonsultit Oy:n harjoitustehtavia.
 * harjoitustehtavat netissa
 * http://kehitys.vetokonsultit.fi/javaharj/
 * 
 *  Tehtävä 3.1
 * 
 * BussiGUI luokka
 * 
 */
package vetokonsultit.olioharjoitukset.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import vetokonsultit.olioharjoitukset.Bussi;

/**
 *
 * @author pasi haverinen
 */
public class BussiGUI extends javax.swing.JFrame {
    
    
      Bussi bussiInstance=new Bussi();

    /** Creates new form BussiGUI */
    public BussiGUI() {
        initComponents();
        
        //lisataan actionListenerit lisaa ja poista painikkeille
        this.jButton_LisaaMatkustaja.addActionListener(new LisaaMatkustajaBtnListener());
        this.jButton_PoistaMatkustaja.addActionListener(new PoistaMatkustajaBtnListener());
        this.jTextField_matkustajienLkm.setText("0");
        this.jLabel_matkustajienlkm.setText("0");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLayeredPane_MatkustajienMaara = new javax.swing.JLayeredPane();
        jLabel_matkustajienlkm_otsikko = new javax.swing.JLabel();
        jTextField_matkustajienLkm = new javax.swing.JTextField();
        jButton_LisaaMatkustaja = new javax.swing.JButton();
        jButton_PoistaMatkustaja = new javax.swing.JToggleButton();
        jLabel_matkustajienlkm = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_matkustajienlkm_otsikko.setText("Matkustajien lkm:");
        jLabel_matkustajienlkm_otsikko.setName(""); // NOI18N
        jLabel_matkustajienlkm_otsikko.setBounds(10, 100, 140, 10);
        jLayeredPane_MatkustajienMaara.add(jLabel_matkustajienlkm_otsikko, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField_matkustajienLkm.setText("Anna lkm");
        jTextField_matkustajienLkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_matkustajienLkmActionPerformed(evt);
            }
        });
        jTextField_matkustajienLkm.setBounds(10, 130, 120, 26);
        jLayeredPane_MatkustajienMaara.add(jTextField_matkustajienLkm, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_LisaaMatkustaja.setText("Lisää Matkustaja");
        jButton_LisaaMatkustaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LisaaMatkustajaActionPerformed(evt);
            }
        });
        jButton_LisaaMatkustaja.setBounds(10, 190, 111, 28);
        jLayeredPane_MatkustajienMaara.add(jButton_LisaaMatkustaja, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_PoistaMatkustaja.setText("Poista Matkustaja");
        jButton_PoistaMatkustaja.setBounds(140, 190, 117, 28);
        jLayeredPane_MatkustajienMaara.add(jButton_PoistaMatkustaja, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel_matkustajienlkm.setText("jLabel1");
        jLabel_matkustajienlkm.setName("jLabel_matkustajienlkm"); // NOI18N
        jLabel_matkustajienlkm.setBounds(130, 100, 70, 16);
        jLayeredPane_MatkustajienMaara.add(jLabel_matkustajienlkm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLabel_matkustajienlkm.getAccessibleContext().setAccessibleName("jLabel_matkustajienlkm");

        jLayeredPane_MatkustajienMaara.setBounds(10, 30, 370, 230);
        desktopPane.add(jLayeredPane_MatkustajienMaara, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

private void jButton_LisaaMatkustajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LisaaMatkustajaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton_LisaaMatkustajaActionPerformed

private void jTextField_matkustajienLkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_matkustajienLkmActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField_matkustajienLkmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BussiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BussiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BussiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BussiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BussiGUI().setVisible(true);
            }
        });
    }
    // LisaaMatkustajaListener
    class LisaaMatkustajaBtnListener implements ActionListener {         
        public void actionPerformed(ActionEvent e) {
            
            try {
                int matkustajiayhteesa = 0, lisamatkustajienLkm = Integer.parseInt(jTextField_matkustajienLkm.getText());
                bussiInstance.nouseeKyytiin(lisamatkustajienLkm);
                matkustajiayhteesa = bussiInstance.montakoIhmista();
                jTextField_matkustajienLkm.setText("0");

                jLabel_matkustajienlkm.setText(String.valueOf(matkustajiayhteesa));

            } catch (NumberFormatException ne) {
            }
                       
        }
    }//PoistaMatkustajaListener
    class PoistaMatkustajaBtnListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            try {
                int matkustajiayhteesa = 0, poistuvienmatkustajienLkm = Integer.parseInt(jTextField_matkustajienLkm.getText());
                bussiInstance.hyppaaPois(poistuvienmatkustajienLkm);
                matkustajiayhteesa = bussiInstance.montakoIhmista();
                jTextField_matkustajienLkm.setText("0");

                jLabel_matkustajienlkm.setText(String.valueOf(matkustajiayhteesa));
            } catch (NumberFormatException ne) {
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton_LisaaMatkustaja;
    private javax.swing.JToggleButton jButton_PoistaMatkustaja;
    private javax.swing.JLabel jLabel_matkustajienlkm;
    private javax.swing.JLabel jLabel_matkustajienlkm_otsikko;
    private javax.swing.JLayeredPane jLayeredPane_MatkustajienMaara;
    private javax.swing.JTextField jTextField_matkustajienLkm;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables
}
